# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/linkaihao/桌面/linux_lkh

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/linkaihao/桌面/linux_lkh

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linkaihao/桌面/linux_lkh/CMakeFiles /home/linkaihao/桌面/linux_lkh/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linkaihao/桌面/linux_lkh/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named linux_lkh

# Build rule for target.
linux_lkh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linux_lkh
.PHONY : linux_lkh

# fast build rule for target.
linux_lkh/fast:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/build
.PHONY : linux_lkh/fast

BPTree.o: BPTree.cpp.o

.PHONY : BPTree.o

# target to build an object file
BPTree.cpp.o:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/BPTree.cpp.o
.PHONY : BPTree.cpp.o

BPTree.i: BPTree.cpp.i

.PHONY : BPTree.i

# target to preprocess a source file
BPTree.cpp.i:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/BPTree.cpp.i
.PHONY : BPTree.cpp.i

BPTree.s: BPTree.cpp.s

.PHONY : BPTree.s

# target to generate assembly for a file
BPTree.cpp.s:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/BPTree.cpp.s
.PHONY : BPTree.cpp.s

CLMutex.o: CLMutex.cpp.o

.PHONY : CLMutex.o

# target to build an object file
CLMutex.cpp.o:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/CLMutex.cpp.o
.PHONY : CLMutex.cpp.o

CLMutex.i: CLMutex.cpp.i

.PHONY : CLMutex.i

# target to preprocess a source file
CLMutex.cpp.i:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/CLMutex.cpp.i
.PHONY : CLMutex.cpp.i

CLMutex.s: CLMutex.cpp.s

.PHONY : CLMutex.s

# target to generate assembly for a file
CLMutex.cpp.s:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/CLMutex.cpp.s
.PHONY : CLMutex.cpp.s

CLThread.o: CLThread.cpp.o

.PHONY : CLThread.o

# target to build an object file
CLThread.cpp.o:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/CLThread.cpp.o
.PHONY : CLThread.cpp.o

CLThread.i: CLThread.cpp.i

.PHONY : CLThread.i

# target to preprocess a source file
CLThread.cpp.i:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/CLThread.cpp.i
.PHONY : CLThread.cpp.i

CLThread.s: CLThread.cpp.s

.PHONY : CLThread.s

# target to generate assembly for a file
CLThread.cpp.s:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/CLThread.cpp.s
.PHONY : CLThread.cpp.s

Record.o: Record.cpp.o

.PHONY : Record.o

# target to build an object file
Record.cpp.o:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/Record.cpp.o
.PHONY : Record.cpp.o

Record.i: Record.cpp.i

.PHONY : Record.i

# target to preprocess a source file
Record.cpp.i:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/Record.cpp.i
.PHONY : Record.cpp.i

Record.s: Record.cpp.s

.PHONY : Record.s

# target to generate assembly for a file
Record.cpp.s:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/Record.cpp.s
.PHONY : Record.cpp.s

TableHelper.o: TableHelper.cpp.o

.PHONY : TableHelper.o

# target to build an object file
TableHelper.cpp.o:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/TableHelper.cpp.o
.PHONY : TableHelper.cpp.o

TableHelper.i: TableHelper.cpp.i

.PHONY : TableHelper.i

# target to preprocess a source file
TableHelper.cpp.i:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/TableHelper.cpp.i
.PHONY : TableHelper.cpp.i

TableHelper.s: TableHelper.cpp.s

.PHONY : TableHelper.s

# target to generate assembly for a file
TableHelper.cpp.s:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/TableHelper.cpp.s
.PHONY : TableHelper.cpp.s

ThreadTest.o: ThreadTest.cpp.o

.PHONY : ThreadTest.o

# target to build an object file
ThreadTest.cpp.o:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/ThreadTest.cpp.o
.PHONY : ThreadTest.cpp.o

ThreadTest.i: ThreadTest.cpp.i

.PHONY : ThreadTest.i

# target to preprocess a source file
ThreadTest.cpp.i:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/ThreadTest.cpp.i
.PHONY : ThreadTest.cpp.i

ThreadTest.s: ThreadTest.cpp.s

.PHONY : ThreadTest.s

# target to generate assembly for a file
ThreadTest.cpp.s:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/ThreadTest.cpp.s
.PHONY : ThreadTest.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/linux_lkh.dir/build.make CMakeFiles/linux_lkh.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... linux_lkh"
	@echo "... BPTree.o"
	@echo "... BPTree.i"
	@echo "... BPTree.s"
	@echo "... CLMutex.o"
	@echo "... CLMutex.i"
	@echo "... CLMutex.s"
	@echo "... CLThread.o"
	@echo "... CLThread.i"
	@echo "... CLThread.s"
	@echo "... Record.o"
	@echo "... Record.i"
	@echo "... Record.s"
	@echo "... TableHelper.o"
	@echo "... TableHelper.i"
	@echo "... TableHelper.s"
	@echo "... ThreadTest.o"
	@echo "... ThreadTest.i"
	@echo "... ThreadTest.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

